apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    name: springboot
    app: spring-app
spec:
  selector:
    name: springboot
    app: spring-app
  type: LoadBalancer  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    
